wowtools_version: "4.0.0"

# Windows Client
wow_dir: "C:\\Program Files (x86)\\World of Warcraft"
wtf_dir: "C:\\Program Files (x86)\\World of Warcraft\\_retail_\\WTF"
backup_dir: "C:\\Program Files (x86)\\World of Warcraft\\_retail_\\Backups\\"
elvui_dir: "C:\\Program Files (x86)\\World of Warcraft\\_retail_\\Interface\\AddOns\\ElvUI\\"
elvui_options_dir: "C:\\Program Files (x86)\\World of Warcraft\\_retail_\\Interface\\AddOns\\ElvUI_OptionsUI\\"
addons_dir: "C:\\Program Files (x86)\\World of Warcraft\\_retail_\\Interface\\AddOns"
curseforge_exe: "C:\\Users\\<USERNAME>\\AppData\\Local\\Programs\\CurseForge\\CurseForge.exe"
retention_rate: 15

# Linux Server
blizzard_clientid: ""
blizzard_clientsecret: ""
discord_webhook_url: ""
wow_token_min: 2000000000
discord_embed_image: "https://media.tenor.com/f42nTKr9aggAAAAC/excited-ronpaul.gif"
