on:
  push:
    tags:
      - "v*"
    branches: [main]
    paths:
      - "versionHelper.go"
  pull_request:
    branches: [main]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.18

    - name: Make build folder
      run: mkdir build

    - name: ls debug
      run: ls -a && pwd

    - name: Build for Windows (amd64)
      run: |
        cd cmd/client && env GOOS=windows GOARCH=amd64 go build -o /home/runner/work/wowtools/wowtools/build/wowtools_client.exe
        cd ../server && env GOOS=windows GOARCH=amd64 go build -o /home/runner/work/wowtools/wowtools/build/wowtools_server.exe

    - name: Build for Linux (amd64)
      run: cd cmd/server && env GOOS=linux GOARCH=amd64 go build -o /home/runner/work/wowtools/wowtools/build/wowtools_server

    # Go Tests are acting up due to the W32 module - I've disabled all the tests but it still spits errors out. Disabling for now as these are all local tests anyways
    #- name: Test
      #run: go test -v ./...

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: WoWTools-AMD64
        path: |
          build/wowtools_client.exe
          build/wowtools_server.exe
          build/wowtools_server
          LICENSE
          README.md
          config.yaml

  pre-release:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3

      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: WoWTools-AMD64

      - name: See file contents
        id: filesinfolder
        run: ls -a /home/runner/work/wowtools/wowtools

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Create Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GO_RELEASER_GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build ${{ steps.date.outputs.date }}-${{ github.run_number }}"
          files: |
            LICENSE
            README.md
            build/wowtools_client.exe
            build/wowtools_server.exe
            build/wowtools_server
            config.yaml
  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v3

      - name: Download Windows Artifacts
        uses: actions/download-artifact@v2
        with:
          name: WoWTools-AMD64

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Create Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GO_RELEASER_GITHUB_TOKEN }}"
          prerelease: false
          files: |
            LICENSE
            README.md
            build/wowtools_client.exe
            build/wowtools_server.exe
            build/wowtools_server
            config.yaml
