on:
  push:
    branches: [ main ]
    tags:
      - "v*"
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Make build folder
      run: mkdir build

    - name: ls debug
      run: ls -a && pwd

    - name: Build for Windows (amd64)
      run: |
        cd cmd/client && env GOOS=windows GOARCH=amd64 go build -o /home/runner/work/wowtools/wowtools/build/wowtools_client.exe
        cd ../server && env GOOS=windows GOARCH=amd64 go build -o /home/runner/work/wowtools/wowtools/build/wowtools_server.exe

    - name: Build for Linux (amd64)
      run: cd cmd/server && env GOOS=linux GOARCH=amd64 go build -o /home/runner/work/wowtools/wowtools/build/wowtools_server

    # Go Tests are acting up due to the W32 module - I've disabled all the tests but it still spits errors out. Disabling for now as these are all local tests anyways
    #- name: Test
      #run: go test -v ./...

    - name: Upload Artifact
      uses: actions/upload-artifact@v2.2.3
      with:
        name: WoWTools-AMD64
        path: |
          build/wowtools_client.exe
          build/wowtools_server.exe
          build/wowtools_server
          LICENSE
          README.md
          config.yaml

      
