on:
  push:
    tags:
      - "v*"
    branches: [main]
    paths:
      - "versionHelper.go"
  pull_request:
    branches: [main]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.18

    - name: Make build folder
      run: mkdir build

    - name: ls debug
      run: ls -a && pwd

    - name: Build for Windows (amd64)
      run: |
        env GOOS=windows GOARCH=amd64 go build -o /home/runner/work/wowtools/wowtools/build/wowtools.exe

    # Go Tests are acting up due to the W32 module - I've disabled all the tests but it still spits errors out. Disabling for now as these are all local tests anyways
    #- name: Test
      #run: go test -v ./...

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: WoWTools-AMD64
        path: |
          build/wowtools.exe

  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v3

      - name: Download Windows Artifacts
        uses: actions/download-artifact@v2
        with:
          name: WoWTools-AMD64

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            wowtools.exe
