on:
  push:
    branches: [ main ]
    tags:
      - "v*"
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Make build folder
      run: mkdir build

    - name: Install versioninfo
      run: go get github.com/josephspurrier/goversioninfo/cmd/goversioninfo

    - name: cd into cmd folder
      run: cd cmd/
      
    - name: Go Generate
      run: go generate

    - name: Build for Windows (amd64)
      run: env GOOS=windows GOARCH=amd64 go build -o build/wowtools.exe

    # Go Tests are acting up due to the W32 module - I've disabled all the tests but it still spits errors out. Disabling for now as these are all local tests anyways
    #- name: Test
      #run: go test -v ./...

    - name: Upload Windows Artifact
      uses: actions/upload-artifact@v2.2.3
      with:
        name: WoWTools-Windows-AMD64
        path: |
          build/wowtools.exe
          LICENSE
          README.md
          wowtools-cli.yml

  pre-release:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2

      - name: Download Windows Artifacts
        uses: actions/download-artifact@v2
        with:
          name: WoWTools-Windows-AMD64
          
      - name: See file contents
        id: filesinfolder
        run: ls -a /home/runner/work/wowtools/wowtools

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Create Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GO_RELEASER_GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build ${{ steps.date.outputs.date }}-${{ github.run_number }}"
          files: |
            LICENSE
            README.md
            build/wowtools.exe
            wowtools-cli.yml
  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v2

      - name: Download Windows Artifacts
        uses: actions/download-artifact@v2
        with:
          name: WoWTools-Windows-AMD64

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Create Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GO_RELEASER_GITHUB_TOKEN }}"
          prerelease: false
          files: |
            LICENSE
            README.md
            build/wowtools.exe
            wowtools-cli.yml

      
