on: 
  release:
    types: [created]

jobs:
  release-linux-amd64:
    name: release Windows
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: wangyoucao577/go-release-action@v1.21
      with:
        github_token: ${{ secrets.GO_RELEASER_GITHUB_TOKEN }}
        goos: windows
        goarch: amd64
