on:
  pull_request:
    branches: [ main ]
jobs:
 pre-release:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2

      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: WoWTools-AMD64
          
      - name: See file contents
        id: filesinfolder
        run: ls -a /home/runner/work/wowtools/wowtools

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Create Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GO_RELEASER_GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build ${{ steps.date.outputs.date }}-${{ github.run_number }}"
          files: |
            LICENSE
            README.md
            build/wowtools_client.exe
            build/wowtools_server.exe
            build/wowtools_server
            config.yaml